sonar.projectKey=Portal_Ciudadano
sonar.projectName=Portal Ciudadano
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/bootstrap/ssr/**,**/public/build/**,**/assets/**,**/imgs/**,**/icons/**,**/fonts/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.ico,**/*.woff,**/*.woff2,**/*.ttf