FROM php:8.5-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libsqlite3-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql pdo_sqlite zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --no-interaction --prefer-dist

RUN php artisan storage:link

EXPOSE 8000

CMD ["php", "artisan", "serve", "--no-reload", "--host=0.0.0.0", "--port=8000"]
